global:
  resolve_timeout: 1m

route:
  receiver: 'slack-default'
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  routes:
    - matchers:
        - severity = "critical"
      receiver: 'slack-critical'
      continue: true
    - matchers:
        - severity = "warning"
      receiver: 'slack-default'

receivers:
  - name: 'slack-default'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#observability'
        send_resolved: true
        title: '{{ if eq .Status "firing" }}🔥{{ else }}✅{{ end }} {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          *Runbook:* {{ .Annotations.runbook_url }}
          {{ end }}

  - name: 'slack-critical'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#oncall'
        send_resolved: true
        title: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          *Runbook:* {{ .Annotations.runbook_url }}
          {{ end }}

inhibit_rules:
  - source_matchers: [alertname = "ServiceDown"]
    target_matchers: [severity = "warning"]
    equal: [service]
